apiVersion: v1
kind: Service
metadata:
  name: publicdata
  labels:
    app: publicdata
spec:
  ports:
  - port: 5000
  selector:
    app: publicdata
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: publicdata-deployment
spec:
  replicas: 1
  strategy:
      type: Recreate
  template:
    metadata:
      labels:
        app: publicdata
    spec:
      containers:
      - name: publicdata
        image: nexus.teamdigitale.test/publicdata:1.0-alpha
        imagePullPolicy: Always
        lifecycle:
          postStart:
            exec:
             command: ["/bin/sh", "-c", "cat /etc/extra_hosts >> /etc/hosts"]
        ports:
        - name: client
          containerPort: 5000
        securityContext:
          privileged: true
          runAsUser: 0
        volumeMounts:
        - name: hosts
          mountPath: /etc/extra_hosts
        - name: config-volume
          mountPath: /daf-dataportal/src/config
      imagePullSecrets:
      - name: regsecret
      volumes:
      - name: hosts
        hostPath:
          path: /etc/hosts
      - name: config-volume
        configMap:
          name: dataportal-conf